package com.example.gameboxone.observability

object AnalyticsEventNames {
    const val APP_LAUNCH = "app_launch"
    const val APP_FIRST_OPEN = "app_first_open"
    const val LEGAL_ACCEPTED = "legal_accepted"
    const val HOME_VIEW = "home_view"
    const val PLAYER_LOGIN_SUCCESS = "player_login_success"
    const val PLAYER_LOGIN_FAILED = "player_login_failed"
    const val GAME_DETAIL_VIEW = "game_detail_view"
    const val TASK_DETAIL_VIEW = "task_detail_view"
    const val GAME_LAUNCH_CLICK = "game_launch_click"
    const val GAME_START = "game_start"
    const val GAME_EXIT = "game_exit"
    const val GAME_PLAY_TIME = "game_play_time"
    const val TASK_ACHIEVED = "task_achieved"
    const val TASK_REWARD_CLAIMED = "task_reward_claimed"
    const val LEVEL_UP = "level_up"
    const val SDK_REFRESH_START = "sdk_refresh_start"
    const val SDK_REFRESH_SUCCESS = "sdk_refresh_success"
    const val SDK_REFRESH_FAIL = "sdk_refresh_fail"
    const val DATA_REFRESH_START = "data_refresh_start"
    const val DATA_REFRESH_COMPLETE = "data_refresh_complete"
    const val DATA_ERROR = "data_error"
    const val GAME_DOWNLOAD_START = "game_download_start"
    const val GAME_DOWNLOAD_SUCCESS = "game_download_success"
    const val GAME_DOWNLOAD_FAIL = "game_download_fail"
    const val AD_SHOW = "ad_show"
    const val AD_COMPLETE = "ad_complete"
    const val AD_ERROR = "ad_error"
    const val CRASH_FATAL = "crash_fatal"
    const val CRASH_NON_FATAL = "crash_non_fatal"
}

